baseURL: 'https://vjarnot.github.io/'
title: 'Zeroth Oughts'
theme: 'PaperModX'
enableEmoji: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

taxonomies:
  # category: categories
  tag: tags
  series: series

permalinks:
  post: '/post/:year/:month/:day/:slug/'

params:
  env: 'production'
  author: 'Voytek Jarnot'
  title: 'Zeroth Oughts'
  description: "My notes in blog form."

# PaperModX
  useCusomtAnalytics: true
  DisableLanguageSwitch: true
  ShowToc: true
  TocSide: 'left'
  TocOpen: true
  ShowWordCount: true
  ShowCodeCopyButtons: true
  ShowPostNavLinks: true
  EnableImageZoom: true

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    lineNumbersInTable: true
    noClasses: false
    style: dracula

menu:
  main:
    - name: Archives
      url: /archives/
      weight: 5
    - name: Tags
      url: /tags/
      weight: 10
    - name: Search
      url: /search/
      weight: 100


# languages:
#   en:
#     languageName: "English"
#     weight: 1
#     menu:
#       main:
#         - name: Tags
#           url: /tags/
#           weight: 1
#         - name: Search
#           url: /search/
#           weight: 10
