baseURL = 'https://vjarnot.github.io/'
languageCode = 'en-us'
title = 'Zeroth Oughts'
theme = 'PaperMod'

[params]
    author = "Voytek Jarnot"

    themeColor = "blue"
    fullWidthTheme = false
    centerTheme = true

[languages]
    [languages.en]
        [languages.en.params.logo]
            logoText = "Zeroth Oughts"
            logoHomeLink = "/"